name: FOAM-FSI

on: push
  
jobs:
    build:
        runs-on: ubuntu-18.04
        container: davidsblom/foam-fsi:latest
        steps:
            - uses: actions/checkout@v2
            - name: cppcheck
              run: |
                    (cd src/fsi && cppcheck -j `nproc` --enable=performance,portability .)
                    (cd src/RBFMeshMotionSolver && cppcheck -j `nproc` --enable=performance,portability .)
                    (cd src/tests && cppcheck -j `nproc` --enable=performance,portability .)
                    (cd applications && cppcheck -j `nproc` --enable=performance,portability .)
            - name: initialize dependencies
              run: |
                    # foam-extend
                    cd /home
                    tar xf foam-extend-3.2.tar.gz && rm foam-extend-3.2.tar.gz
                    . foam-extend-3.2/etc/prefs.sh && . foam-extend-3.2/etc/bashrc

                    # boost
                    cd /home
                    ln -s /home/boost_1_61_0 boost
                    cp boost/stage/lib/* $FOAM_LIBBIN/
    
                    # petsc
                    ln -s /home/petsc-3.6.4 petsc
                    cp petsc/x86_64/lib/lib* ${FOAM_LIBBIN}/
    
                    # deal.II
                    ln -s /home/dealii-8.4.1 dealii
                    cp dealii/bin/lib/libdeal* ${FOAM_LIBBIN}/
    
                    # googletest
                    ln -s /home/googletest-release-1.8.0 gtest
                    cp gtest/install/lib/lib* ${FOAM_LIBBIN}/
    
                    # yaml-cpp
                    ln -s /home/yaml-cpp-release-0.5.3 yaml-cpp
                    cp yaml-cpp/install/lib/libyaml-cpp* ${FOAM_LIBBIN}/
            - name: elemental
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    mkdir -p src/thirdParty/elemental
                    cd src/thirdParty/elemental
                    git clone https://github.com/elemental/Elemental .
                    ls 
                    mkdir -p build install && cd build
    
                    cmake \
                        -D CMAKE_INSTALL_PREFIX=`pwd`/../install \
                        -D INSTALL_PYTHON_PACKAGE=OFF \
                        -D CMAKE_BUILD_TYPE=Release \
                        -D EL_DISABLE_PARMETIS=TRUE \
                        -D CMAKE_CXX_COMPILER=mpicxx \
                        -D CMAKE_C_COMPILER=mpicc \
                        -D CMAKE_Fortran_COMPILER=mpif90 \
                        -D EL_DISABLE_SCALAPACK=TRUE \
                        -D GFORTRAN_LIB=/usr/lib/gcc/x86_64-linux-gnu/6 \
                        ..
    
                    make -j `nproc`
                    make install
                    cd ..
                    cp install/lib/*.so* $FOAM_LIBBIN/
                    rm -rf build
            - name: precice
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/thirdParty && ./compile_precice
            - name: boundary conditions
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    wmakeLnInclude src/boundaryConditions
                    wmakeLnInclude src/fvSchemes
                    wmakeLnInclude src/fsi
                    wmakeLnInclude src/RBFMeshMotionSolver
                    wmakeLnInclude src/SRFModelAbs
                    wmake libso src/boundaryConditions
            - name: schemes
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    wmake libso src/fvSchemes
            - name: fsi
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    wmake libso src/fsi
            - name: radial basis function mesh motion solver
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    wmake libso src/RBFMeshMotionSolver
            - name: solvers
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd applications/solvers/fsi && wmake all
                    cd ../ && wmake unsteadyPUCoupledFoam
            - name: test app
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests && wmake all
            - name: test sdc
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests && python runTests.py testsuite-sdc
            - name: test sdc-fsi
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests && python runTests.py testsuite-sdc-fsi
            - name: test rbf
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests && python runTests.py testsuite-rbf
                    mpirun -np 4 --allow-run-as-root testsuite-rbf
            - name: test spacemapping
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests && python runTests.py testsuite-spacemapping
            - name: test fsi
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests && python runTests.py testsuite-fsi
            - name: test dealii
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests && python runTests.py testsuite-dealii
            - name: uncrustify
              run: |
                    (cd /home/foam-extend-3.2 && . etc/prefs.sh && . etc/bashrc)
                    cd src/tests/tutorials && python testsuite.py
                    rm -rf * .git* .travis.yml .uncrustify.cfg
